# Generated by Django 5.0.4 on 2024-06-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AirQualityData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pm25", models.FloatField(blank=True, null=True)),
                ("pm10", models.FloatField(blank=True, null=True)),
                ("no", models.FloatField(blank=True, null=True)),
                ("no2", models.FloatField(blank=True, null=True)),
                ("nox", models.FloatField(blank=True, null=True)),
                ("nh3", models.FloatField(blank=True, null=True)),
                ("co", models.FloatField(blank=True, null=True)),
                ("so2", models.FloatField(blank=True, null=True)),
                ("o3", models.FloatField(blank=True, null=True)),
                ("benzene", models.FloatField(blank=True, null=True)),
                ("toluene", models.FloatField(blank=True, null=True)),
                ("xylene", models.FloatField(blank=True, null=True)),
                ("aqi", models.FloatField(blank=True, null=True)),
                ("label", models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name="UserPredictModel",
        ),
    ]
